da-in/algorithm-study

- Programmers - 고득점 Kit/해시_포켓몬/dain.py
해시_포켓몬, 스택/큐_같은 숫자는 싫어 풀이입니다.🙂
해시 테이블에 접근하는 부분이 효율적인지 모르겠습니다.
- #1 
- #2
> 2023-01-20 dain.py

- Warming Up/삼총사/dain.py
- Warming Up/콜라 문제/dain.py
삼총사 문제는 `3중 for문`으로 순회를 돌며 풀까 하다가 `itertools` 라이브러리를 사용했습니다.
콜라 문제는 재귀를 이용해서 풀었습니다.
- `itertools` 는 반복되는 데이터를 처리하는 기능을 포함하고 있는 라이브러리이다.
```python
itertools.permutations(iterable, r=None) # 순열 튜플들 반환
itertools.combinations(iterable, r) # 조합 튜플들 반환
```
- 파이썬의 기본 재귀 깊이 제한은 `1000`밖에 되지 않고, 이를 초과하면 `런타임에러` 가 발생한다.  
따라서 파이썬 재귀 문제 풀이시 아래와 같이 재귀 깊이 제한을 풀어주어야한다.
```
sys.setrecursionlimit(10**6)
```
- #4 
- #6
> [23-01-26] dain

- Warming Up/삼총사/hyuksoon.py
- Warming Up/콜라 문제/hyuksoon.py
삼총사 문제는 이분탐색을 이용하여 풀이했습니다.
주어진 배열에서 a,b,c 세 숫자를 골라 0을 만드는 문제인데,
2중 for문을 통해 먼저 a,b를 고르고 나머지 c는 0-(a+b)인 값이어야 합니다.
이때 c를 찾는 이분탐색 함수를 구현할까 했지만 같은 값이 여러번 등장할 수 있다는 조건때문에 파이썬의 bisect를 사용했습니다.
+ 정확한 시간복잡도는,, 모르겠습니다 ㅎㅎ,, 시간복잡도 구하는 연습을 스터디로 진행해도 좋을것 같습니다. 
콜라 문제는 단순히 주어진 병의 갯수가 문제에 조건으로 나와있는 숫자보다 작을 때 까지 주어진 프로세스를 반복하는 방식으로 구현했습니다.
- #4 
- #6
> [23-01-26] hyuksoon

- Warming Up/삼총사/seungyeon.py
- Warming Up/콜라 문제/seungyeon.py
삼총사 문제는 단순 삼중 포문을 이용해 해결 하였습니다. python으로 for문 구현하느라 조금 힘들었습니다.
콜라 문제는 문제 읽은 그대로 구현했습니다.
- #4 
- #6
> [23-01-26] seungyeon

- Warming Up/삼총사/kyuhyun.py
- Warming Up/콜라 문제/kyuhyun.py
삼총사 문제는 파이썬 왕초보 스타일로 삼중 for문 사용했습니다! 풀이보니 간단해결 되더라구요,,
for문도 더 간략한 표현 방식이 있다면 알려주세요오 
콜라문제는 몫 + 나머지를 계속 나눠주는 방식으로 풀었습니다 :) 
- #4   
- #6
> [23-01-26] kyuhyun

- Warming Up/개인정보 수집 유효기간/dain.py
- Warming Up/과일 장수/dain.py
**개인정보 수집 유효기간**
- 각 약관의 식별자가 문자열 형태이고 자주 참조되므로 `dictionary 자료형`으로 저장하여 사용했습니다.
- 모든 개인 정보의 유효기간을 계산하여 오늘 날짜보다 빠르면 인덱스를 정답 배열에 추가했습니다.
**과일 장수**
- 과일을 `점수` 에 따라 `정렬`하여 큰 순서대로 과일 상자에 담았을 때 `최대 이익`입니다.
- `각 상자에 마지막으로 담기는 과일들의 점수` * `한 상자에 들어가는 사과의 수(m)`
- #11 
- #12
> [23-01-27] dain

- Warming Up/개인정보 수집 유효기간/doha.py
- Warming Up/과일 장수/doha.py
**개인정보 수집 유효기간**
데이터를 가독성있게 분리하는(특히 문자열) 과정을 좀 빡세게 했습니다.
유효기간 타입(terms)은 따로 딕셔너리를 사용해서 편하게 썼고, 
문제 잘 보면 모든 달은 28일로 고정되어있길래, 일 계산하는 함수 따로 만들어서 비교하기 편하게 했습니다
**과일 장수**
파이썬은 신인가? 싶을 정도로 반복문으로 가볍게 끝냈는데, 
자바로 바꾸면서 역순으로 접근하던 기존 방식을 하려니 -> int[] 를 Integer[] 로 바꿔주는게 번거롭더라구요
그래서 그냥 역순으로 안하고 그냥 sort만 해서 반복문을 역방향으로 돌렸습니다.
파이썬 최고
- #11 
- #12
> [23-01-27] doha

- Warming Up/개인정보 수집 유효기간/hyuksoon.py
- Warming Up/과일 장수/hyuksoon.py
과일 장수
역순으로 정렬해서 갯수만큼 담고 마지막에 담기는 친구가 가장 낮을것으로 예상되기에 걔*갯수 했습니다.
개인정보 수집 유효기간
파이썬 split 사용해서 풀이했습니다. 달마다 날짜를 같게 줘서 숫자 곱해서 계산하기 수월했습니다
- #12
- #11
> [23-01-27] hyuksoon

- Warming Up/개인정보 수집 유효기간/seungyeon.py
- Warming Up/과일 장수/seungyeon.py
- 배열을 정렬하여 index값을 이용해 풀었습니다.
- terms 입력값을 파싱하여 딕셔너리에 저장하였습니다.
- privacies 값을 파싱하여 terms 딕셔너리 (dict) 에서 해당 값을 가져오도록 했습니다.
- 딕셔너리에서 가져온 유효기간 값을 이용하여 날짜 계산을 해주었습니다.
- 날짜 파싱할 때 리스트 **list(map(int,input.split(".")))**를 사용하였습니다.
- 날짜 계산이 매우 복잡하고 어려웠습니다... 28일 곱하는 날짜계산으로 할걸 그랬습니다 .. 
- #11 
- #12
> [23-01-27] seungyeon

- Warming Up/개인정보 수집 유효기간/kyuhyun.py
- Warming Up/과일 장수/kyuhyun.py
개인정보 수집 유효기간은 음 내용은 별거 없지만 최대한 간략하고 빠르게 할 방법을 고민하다보니 조금 오래 걸렸습니다
풀긴 풀었지만 부족한 느낌이네요,, re 라이브러리를 통해 문자열 중 숫자만 빼오는 함수를 이용했습니다
.과일장수는 정렬을 통해서 박스의 담기는 과일 갯수로 짤라서 계산했습니다.
- #11
- #12
> [23-01-27] kyuhyun

- Warming Up/뒤에 있는 큰 수 찾기/hyuksoon.py
- Warming Up/마법의 엘리베이터/hyuksoon.py
먼저 나온 숫자가 뒤에 나온 숫자보다 더 늦게 자신보다 큰 수를 찾을 수도 있기 때문에
힙를 이용해서 들어온 순서에 상관없이 가장 작은 수를 팝 하도록 하였습니다.
이때 힙에 넣을 때, 인덱스 번호를 같이 넣어서 answer배열을 갱신할 수 있도록 하였습니다.
사실 처음엔 스택으로 풀다가 순서가 뒤죽박죽인것 때문에 힙을 이용한건데 "다른 사람 풀이" 보니깐 스택으로 깔끔하게 푼게 있네요.. 심지어 훨씬 빨라요..
그렇지만 힙은 매우 유용하다고 생각해요 깊이 생각하지 않고? 문제를 풀게 해주는것 같아요 다른 자료구조를 사용했을 때 신경써야 할 디테일을 재껴버려도 되는게 좋은것 같슴다
```
import heapq
heap = []
heappush(heap, 4) //삽입
heappush(heap, 1)
heappush(heap, 7)
heappush(heap, 3)
print(heappop(heap)) //pop
> 1      //가장 작은 값이 튀어나옴
삽입하는 요소가 배열이라면 배열의 첫번째 요소를 기준으로 가장 작은 값이 pop됩니다.
```
엣지 케이스 생각을 못해서 좀 걸린 문제
"질문하기" 눌러보기 싫어서 한참 생각했는데 생각하고 보니깐 그렇게 어려운건 아니었던것 같습니다.
층을 나타내는 숫자의 1의 자리부터 숫자를 빼거나 더해서 끝자리를 0으로 맞춰주도록 하고 MSB를 마지막으로 더해주는걸 생각했는데, 1의 자리가 5이고 10의 자리가 5미만인 경우는 5를 뺴는게 빠르고 5 이상인 경우는 5를 더하는게 빠르더라고요?? 이게 사실 정확한건진 잘 모르겠지만요 제가 미처 발견하지 못했지만 우연찮게 …
> [23-01-30] hyuksoon

- Warming Up/뒤에 있는 큰 수 찾기/kyuhyun.py
- Warming Up/마법의 엘레베이터/kyuhyun.py
1. 뒤에 있는 큰 수 찾기
문제의 포인트는 개인적으로 answer 배열에 추가하는 방식이 아닌 '-1' 로 세팅을 하고 시작하는 것이라고 느꼈습니다. 여러가지 방식으로 생각을 해보았는데 리스트를 스택같이 이용을 해서 수와 인덱스를 같이 넣어놨다가 해당이 된다면 뺴주는 식으로 구현을 했습니다. 
2. 마법의 엘레베이터
음 이 문제의 핵심은 아마 5를 기준으로 나누는 것이지 않을까 합니다. 만약 5라면 그 앞자리수가 어떤 수이냐에 따라 올리고 내릴수도 있습니다. 이 케이스를 인지하고 단순하게 범위별로 나누어주는 방식으로 구현하였습니다. 후후
- #19 
- #20
> [23-01-30] kyuhyun

- Warming Up/뒤에 있는 큰 수 찾기/doha.py
- Warming Up/마법의 엘리베이터/doha.py
생각보다 오래 걸렸어요, stack을 생각해내는데 오래 걸린듯
처음에 이중 for문으로 하다가 정확도 78점 나와서 아 이거 딱봐도 stack 아니면 heap 문제겠구나 파악했습니다
하지만 stack을 어떻게 써야 효율적일까 고민하다가 시간을 많이 썼어요(아직 미숙하기도 하고)
index의 값을 유지하면 되나? 싶어서 적용한 방법이 잘 되어서 다행이었습니다.
자세한 설명은 주석에 달아놨으니 같이 보면서 설명해드릴게요
이거는 규칙을 찾는게 좀 힘들었지만, 손으로 슥슥 경우의수 생각하면서 해보니 금방 풀었습니다.
주의해야할게, 단순히 5이상이면 자릿수 올려서 계산하는게 아니라, 5일때 앞자리가 어떤 숫자인지에 따라 또 다른 경우가 있어서
이부분 주의해서 풀었더니 다 통과했습니다.
- #19 
- #20
> [23-01-30] doha

- Warming Up/뒤에 있는 큰 수 찾기/seungyeon.py
- Warming Up/마법의 엘리베이터/seungyeon.py
- 다른 자료구조 안만들고 입력받은 number를 pop 해서 일련의 과정을 거친 후 answer.append 하는게 꿈이었는데 꿈을 이루지 못하고 꿈꾸러 갑니다 .. 
- 그래서 우선순위 큐로 numbers 정렬하고 비교하면서 할까 했는데 그건 너무 비효율적인거같아요 그럴거면 굳이?
- 무슨 마법에 걸려서 DFS에 빠졌어요
- 최소한의 수 를 구하라는 말에 DFS에 꽃혀서 이리저리 해보다가 성공했답니다.
- #19 
- #20
> [23-01-30] seungyeon

- Warming Up/뒤에 있는 큰 수 찾기/dain.py
- Warming Up/마법의 엘리베이터/dain.py
**뒤에 있는 큰 수 찾기**
- 이 문제 Do it 알고리즘 코딩테스트 책에서 봤던 문제더라구요.
- 근데 그 풀이가 기가 막힌 나머지 이번에도 떠올리지 못함.
- 다른 풀이로 살짝 고민하다보니 그때의 풀이가 떠올라서 풀었습니다. 소개해드릴게요.
**마법의 엘리베이터**
- 여기서 엣지케이스를 찾는데 애먹었습니다
- 그런데 풀었는데 왜 인지 잘 모르겠어요. 두 번째 조건문에 `storey // 10 % 10 >= 5` 를 `storey // 10 % 10 > 5`로 하면 실패가 뜨더라구요.
- #19 
- #20
> [23-01-30] dain.py

- Programmers - 고득점 Kit/[스택-큐] 같은 숫자는 싫어/doha.py
- Programmers - 고득점 Kit/[스택-큐] 올바른 괄호/doha.py
- Programmers - 고득점 Kit/[해시] 폰켓몬/doha.py
중복 안되게 조건 넣어서 **answer** 배열에 append 해줬습니다.
문제 카테고리가 스택/큐라서 거기에 충실했어요(사실 안써도 풀 수 있었는데)
저는 **Stack**을 사용해서 담고, 비교해서 pop했습니다
마지막에 Stack이 비어있으면 True, 아니면 False로 return 했어요
return에 **삼항연산자** 사용했습니다
- #1 
- #2 
- #30
> [23-01-31] doha.py

- Programmers - 고득점 Kit/[스택-큐] 같은 숫자는 싫어/dain.py
- Programmers - 고득점 Kit/[스택-큐] 올바른 괄호/dain.py
- Programmers - 고득점 Kit/[해시] 폰켓몬/dain.py
- **폰켓몬** | 종류의 수와 `N/2` 중 더 작은 것이 정답
- **올바른 괄호** | 스택에 쌓으며 `(` 다음 `)`가 들어갈 차례면 `pop()`
- **같은 숫자는 싫어** | 스택에 가장 위 숫자와 다를 때에만 `append()`
- #1 
- #2 
- #30
> [23-01-31] dain.py

- Programmers - 고득점 Kit/[스택-큐] 올바른 괄호/seungyeon.py
- Programmers - 고득점 Kit/[해시] 폰켓몬/seungyeon.py
- set을 사용해 풀었습니다.
- 일단 "("를 넣고 생각해보았습니다.
- #1 
- #2
> [23-01-31] seungyeon.py

- Programmers - 고득점 Kit/[정렬] K번째수/hyuksoon.py
- Programmers - 고득점 Kit/[정렬] 가장 큰 수/hyuksoon.py
- Programmers - 고득점 Kit/[힙] 더 맵게/hyuksoon.py
- K번째 수
그냥 매번 했는데 매번 소트 안하는 법은 없나요? 갈켜주실 분?
- 가장 큰 수
갱장히 스트레스 받고 풀었습니다...
343, 34 중에는 34가 먼저 나와야 하고
323, 32 중에는 323이 먼저 나와야 하길래
울까 하다가
1,2,3,,,1,2,3,,중얼중얼 하다가 갑자기 초등학교때 배운 최소공배수가 떠올랐습니다.
1000이하니깐 세자리까지만 등장하잖아요?
그래서 모든 숫자를 6자리로 바꾸었습니다.
3-> 333333
34-> 343434
343 -> 343343
그렇게 해서 정렬하니깐 풀리더라구요
굉장히 야매스럽습니다
조건이 1000 넘어가면 이 방법은 안먹히고
0과 1000은 처리하지 못해서 따로 처리해줬습니다 ㅋ.ㅋ
문제 맛있네요
- 더 맵게
힙으로 풀긴 했는데 항상 길이가 2이상이어야 하잖아요
근데 매번 길이를 구하자니 배열길이가 최대 100만이라 부담될거 같아서
그냥 try-except 써버렸는데 이거의 시간복잡도는 모르겠습니다?
- #34 
- #35 
- #36
> [23-02-01] hyuksoon.py

- Programmers - 고득점 Kit/[정렬] K번째수/doha.py
- Programmers - 고득점 Kit/[정렬] 가장 큰 수/doha.py
- Programmers - 고득점 Kit/[힙] 더 맵게/doha.py
- ✨ 효과 만점 코딩테스트 Cheat Sheet!/🍯 코드를 줄여줄 꿀 라이브러리 모음.md
파이썬 라이브러리 heapq 사용해서 해결했습니다
배열 슬라이스와 sorted() 사용했습니다
>일동 묵념  
처음에 각 수마다 중복되는 수들을 조합하는 permutations만 사용하다가 시간초과가 많이 났어요
진짜 다양한 방법으로 시간초과를 없애려고 했지만 결국 실패 후, 라이브러리 검색해보다가
sorted()함수의 **치트키** [functools.cmp_to_key] 를 발견하고 응용해서 사용했습니다. -> 자세한 내용은 치트 시트에 올리겠습니다
각 숫자를 문자열로 받아서 비교 및 정렬 이후에 합쳐서 숫자로 바꾸고 다시 문자로 바꿔서 return 했습니다.(0000때문에)
- #34
- #35 
- #36
> [23-02-01] doha.py

- Programmers - 고득점 Kit/[그리디] 조이스틱/dain.py
- Programmers - 고득점 Kit/[완전탐색] 소수 찾기/dain.py
- Programmers - 고득점 Kit/[완전탐색] 최소직사각형/dain.py
- **최소 직사각형** | 명함의 긴 부분을 무조건 지갑의 가로라고 생각하고 풀이. 명함 순회하며 최대값으로 갱신.
- **소수 찾기** | 에라토스테네스의 채_(숫자를 1부터 모든 수로 나누어보고 나누어떨어지면 소수에서 제외)_ 방식으로 풀이.
- **조이스틱** | 
- `조작 횟수 최솟값` = `최소 알파벳 변경 횟수` + `최소 커서 이동 횟수`
- `최소 알파벳 변경 횟수` : `ord()` 아스키코드를 숫자로 변환. 앞으로 / 뒤로 변경했을 때 값 구해서 비교.
-  `최소 커서 이동 횟수` : 모든 경우를 계산. `point` : "어디까지 갔다가 돌아갈 것인가." 를 기준으로 계산.
- #42 
- #43 
- #44
> [23-02-02] dain.py

- Programmers - 고득점 Kit/[완전 탐색] 소수 찾기/kyuhyun.py
- Programmers - 고득점 Kit/[완전 탐색] 최소 직사각형/kyuhyun.py
1. 최소 직사각형
그냥 차례대로 명함을 하나씩 넣으면서 만들 수 있는 최소의 크기를 계속 업데이트 했습니다
깔끔하진 않아서 마음엔 안드네요,,,
2. 소수 찾기
itertools의 permutations를 이용해서 만들 수 있는 모든 경우를 고려하고, 방문리스트를 통해 이미 방문했다면 넘어가도록 처리 했습니다  
역시 깔끔하진 않네요,,
3. 조이 스틱
풀다가 노트북 주먹으로 씨게 칠뻔했어요. 그래도 50점은 맞았답니다? 하지만 결국 못풀었어요,,핵심은 왼쪽, 오른쪽 경우를 파악하는 것 같은데 질문하기를 봐도 뭔 소리인가 싶더라고요,,,진짜 그리디?는 아닌? 것? 같아요 
- #42 
- #43
> [23-02-02] kyuhyun.py

- Programmers - 고득점 Kit/[완전탐색] 소수찾기/hyuksoon.py
- Programmers - 고득점 Kit/[완전탐색] 최소직사각형/hyuksoon.py
- 최소 직사각형
큰것끼리 묶고, 작은것끼리 묶어서 max(큰거)*max(작은거)
- 소수찾기
에라토스테네스의 체..
+에라토스테네스의 체를 모르면 못푸는게 억울해서 탐색으로 풀어봤는데 풀리네요
방문 체크해서 횟수 줄였어요
- 조이스틱
코드 없습니다...풀다가 너무 화남
근데 제일 상위에 있던 답안 보니깐 아예 완탐으로 푼것 같더라고요..?
그리디라는 라벨을 보지 말걸 그랬습니다..
- #42 
- #43
- #44
> [23-02-02] hyuksoon.py

- Programmers - 고득점 Kit/[그리디] 조이스틱/doha.py
- Programmers - 고득점 Kit/[완전탐색] 소수 찾기/doha.py
- Programmers - 고득점 Kit/[완전탐색] 최소직사각형/doha.py
가로 세로에 제한 두지 않고 풀었습니다
permutation 활용해서 모든 조합 구한다음, 
각 값들을 제곱근까지 확인해서 소수 판별 후 정리해서 짜잔
- #42 
- #43 
- #44
> [23-02-02] doha.py

- Programmers - 고득점 Kit/[동적계획법] N으로 표현/seungyeon.py
- Programmers - 고득점 Kit/[완전탐색] 소수 찾기/seungyeon.py
- Programmers - 고득점 Kit/[완전탐색] 최소직사각형/seungyeon.py
- Programmers - 고득점 Kit/[탐욕법] 조이스틱/seungyeon.py
- Programmers - 고득점 Kit/[탐욕법] 체육복/seungyeon.py
- 문자열 슬라이스 해서 permutation 이용했습니다.
- 가로 세로 길이 두 값 중 최대값을 가로에 넣고, 최소값을 세로에 넣어 가로의 최대값, 세로의 최대값을 이용하였습니다.
- 싫어요
- BFS 풀이도 있던데 .. 
- #42 
- #43 
- #44
> [23-02-02] seungyeon.py

- Programmers - 고득점 Kit/[DP] N으로 표현/dain.py
- Programmers - 고득점 Kit/[그리디] 체육복/dain.py
- **체육복** | 그리디. reserve 순회하며 앞, 뒷 번호 학생이 체육복이 없으면 준다. (앞 번호 우선)
- **N으로 표현** | DP. `2개로 만들 수 있는 수` = `1개로 만들 수 있는 수` { `+`, `-`, `*`, `//` } `1개로 만들 수 있는 수` & `NN`
- #50  
- #51
> [23-02-03] dain.py

- Programmers - 고득점 Kit/[DP] N으로 표현/kyuhyun.py
- Programmers - 고득점 Kit/[그리디] 체육복/kyuhyun.py
1. 체육복
저는 보자마자 학생 수 만큼의 새로운 리스트를 생성하고, 0, 1, 2로 표현해서 0을 카운트해볼까,,가 떠올라서 그렇게 구현을 해봤습니다!
칠칠맞은 여벌의 체육복까지 잃어버린 학생을 고려하는 것이 포인트인것 같습니다아 저는 `set` 으로 처리를 해주었어요 
2. N으로 표현
DP는 점화식만 생각해 낸다면 그 후는 구현만 하면 되기 때문에  점화식을 생각하다가 머리가 터져버릴뻔 했어요,, 🤯🤯 그래도 다행히 노가다로 해보다가 발견해서 잘 구현을 했답니다. DP는 푸는 맛이 있네요  
- #50 
- #51
> [23-02-03] kyuhyun.py

- Programmers - 고득점 Kit/[DP] N으로 표현/hyuksoon.py
- Programmers - 고득점 Kit/[그리디] 체육복/hyuksoon.py
- N으로 표현
dp라는게 안써있었다면 못풀지 않았을까 생각이 들었슴다,,
첨엔 사실 틀린 점화식을 생각했었어요
dp[x]=x라는 숫자를 만드는데 필요한 숫자N의 갯수
로 생각하다가 그러면 너무 커지기도 하고 12의 사칙연산을 다 생각해야한단 점에서 틀렸다는걸 알았고
어찌저찌 하다가 최대 8개까지만 쓸 수 있다는걸 그제서야 발견해서 풀었습니다.
- 체육복
이것도 조이스틱처럼 예전에 풀었었는데 지금은 틀린 코드가 되어있었어요
그땐 교집합 구하느라 인터섹션 어쩌구 사용했었는데
익숙한 코드가 아니라서 실전가면 생각 안날까봐 없이 풀어봤슴니다(찾아보기 귀찮아서는 아님 ㅎㅎ,,사실 "a in list" 쓰기 싫어서 첨에 해시로 푼건데 풀다보니까 점점 귀찮아서 그냥 썼어요)
- #50 
- #51
> [23-02-03] hyuksoon.py

- Programmers - 고득점 Kit/[DFS-BFS] 타겟 넘버/doha.py
- Programmers - 고득점 Kit/[이분탐색] 입국심사/doha.py
DFS 문제 치고 쉬워서 할만했습니다
이분탐색 처음 써봤는데 이렇게 쓰는게 맞나요
여러모로 유용한거 같긴 합니다 신선한 접근법이라 공부가 됐어요
- #57 
- #58
> [23-02-06] doha.py

- Programmers - 고득점 Kit/[DFS-BFS] 타겟 넘버/kyuhyun.py
- Programmers - 고득점 Kit/[이분탐색] 입국심사/kyuhyun.py
1. 타겟넘버
그냥 처음부터 인덱스 가지고 댕기면서 +, - 해주었습니다. BFS, DFS 두가지 다 풀어봤어요
2. 입국심사
처음엔 반으로 나누는? 기준이 뭘까 고민을 했습니다. 결론은 걸리는 시간의 배수 형태로 비교하는 규칙을 발견하고 구현했습니다
- #57 
- #58
> [23-02-06] kyuhyun.py

- Programmers - 고득점 Kit/[DFS-BFS] 타겟 넘버/hyuksoon.py
- Programmers - 고득점 Kit/[이분탐색] 입국심사/hyuksoon.py
- 타겟넘버
더하기뺴기밖에 없어서 첫 숫자부터 시작해서 재귀로 풀었습니다
- 입국심사
- #57 
- #58
> [23-02-06] hyuksoon.py

- Programmers - 고득점 Kit/[DFS-BFS] 타겟 넘버/seungyeon.py
- Programmers - 고득점 Kit/[이분탐색] 입국심사/seungyeon.py
- dfs 함수 인자가 길어서 조금 아쉽습니다.
- 생각보다 쉬워서 놀랐습니다.
- mid // time : 최소시간동안 심사 가능한 사람의 수 
- #57 
- #58 
- #0
> [23-02-06] seungyeon.py

- Programmers - 고득점 Kit/[그래프] 가장 먼 노드/kyuhyun.py
- README.md
1. 가장 먼 노드
- bfs로 풀었습니다아
- #65
> [23-02-07] kyuhyun.py

- Programmers - 고득점 Kit/[그래프] 가장 먼 노드/hyuksoon.py
> [23-02-07] hyuksoon.py

- Programmers - 고득점 Kit/[스택-큐] 기능개발/doha.py
- Programmers - 고득점 Kit/[해시] 전화번호 목록/doha.py
원래 아무생각없이 풀다가 시간초과떠서 시간복잡도를 줄일 방법을 찾던 중에
**'딕셔너리' in (key값)** 이렇게 찾으면 **O(1)** 이길래 바로 적용시켰습니다
그래서 접두사 경우의 수를 모두 키값으로 넣고 돌렸더니 짧고 간단하게 해결했어요
**deque** 이용해서 풀긴 했는데.. stack으로 해도 될거같아요
테스트케이스 통과 못하는 경우가 생겨서 잘 생각해보다가 
어이없는 실수를 발견하고 **반올림 함수** 써서 해결했습니다.
- #71 
- #72
> [23-02-08] doha.py

- Programmers - 고득점 Kit/[스택-큐] 기능개발/dain.py
- Programmers - 고득점 Kit/[해시] 전화번호 목록/dain.py
- **전화번호 목록** | 딕셔너리로 간단한 Trie 자료구조를 구현했습니다.
- **기능개발** | 우와 마참내 zip을 사용했어요!😆 각 기능 개발 남은 날짜를 계산하고, 스택...이라기엔 지금보니 애매하네요. 일단 쌓긴 했습니다.
- #71 
- #72
> [23-02-08] dain.py

- Programmers - 고득점 Kit/[스택-큐] 기능개발/hyuksoon.py
- Programmers - 고득점 Kit/[해시] 전화번호 목록/hyuksoon.py
- 기능 개발
깔끔하지 못해 아쉽슴다..
- 전화번호 목록
첨에 시간초과 났는데 왜 났는지 모르겠음??!! 거의 동일한데..
- #71
- #72
> [23-02-08] hyuksoon.py

- Programmers - 고득점 Kit/[스택-큐] 기능개발/kyuhyun.py
- Programmers - 고득점 Kit/[해쉬] 전화번호 목록/kyuhyun.py
- Programmers - 고득점 Kit/[해시] 완주하지 못한 선수/kyuhyun.py
- Programmers - 고득점 Kit/[힙] 디스크 컨트롤러/kyuhyun.py
1. 전화번호 목록
- 같은 수가 포함되어 있다면 sort 했을 때 붙어있지 않을까 하는 생각으로 풀었습니다. 
</br>
2. 기능개발
- 다양한 풀이가 가능할거 같은데 그냥 최대한 직관적이고, 깔끔하게 풀려고 했습니다. 
- 리버스한 이유는 시간복잡도 때문에,,
- #71 
- #72
> [23-02-08] kyuhyun.py

- Programmers - 고득점 Kit/[해시] 완주하지 못한 선수/hyuksoon.py
- Programmers - 고득점 Kit/[힙] 디스크 컨트롤러/hyuksoon.py
- 완주하지 못한 선수
해시로 풀었습니다
- 디스크 컨트롤러
어거지로 풀었습니다
- #79 
- #80
> [23-02-09] hyuksoon.py

- Programmers - 고득점 Kit/[해시] 완주하지 못한 선수/kyuhyun.py
- Programmers - 고득점 Kit/[힙] 디스크 컨트롤러/kyuhyun.py
1. 완주하지 못한 선수
- 해시로 풀고 싶었는데 정렬만큼 간단한게 안떠올라서,, 그냥 정렬로 풀었습니다
2. 디스크 컨트롤러
- 힙으로 풀었습니다
- 여러 업무 중 가장 작업시간이 짧은 걸 우선적으로 처리 했습니다아
- #80
- #79
> [23-02-09] kyuhyun.py

- Programmers - 고득점 Kit/[그리디] 큰 수 만들기/hyuksoon.py
- Programmers - 고득점 Kit/[정렬] H-Index/hyuksoon.py
- 큰 수 만들기
그리디라는걸 모르고 풀었으면 바로 풀었을거 같아요 차라리 ㅠ
- H-index
🤬
- #87 
- #88
> [23-02-10] hyuksoon.py

- Programmers - 고득점 Kit/[DP] 정수 삼각형/kyuhyun.py
- Programmers - 고득점 Kit/[완전탐색] 모의고사/kyuhyun.py
1. 모의고사
- 수포자 3명이 정해져 있어서 5 / 8 / 10 단위로 나눠서 처리했습니다.
2. 정수 삼각형
- DP로 풀었고,,,음,,한 줄씩 내려가면서 양 쪽끝은 그냥 더해주고, 중간은 더해서 나오는 두 수 중 최대인 수를 골라서 집어 넣었습니다.
- #94 
- #93
> [23-02-14] kyuhyun.py

- Programmers - 고득점 Kit/[DP] 정수 삼각형/doha.py
- Programmers - 고득점 Kit/[완전탐색] 모의고사/doha.py
구간합이 생각나서, 위에서부터 차례대로 더하면서 새로운 피라미드(를 가장한 2차원 배열)를 만들었습니다
DP로 푸니까 코드가 간결해서 좋네용
처음 인덱스, 마지막 인덱스일때는 경우가 1가지라서 그대로 넣고, 그 외는 최댓값만 집어넣어서 구현했습니다
1번, 2번, 3번 사람 경우의수가 고정되어있어서 오히려 편했어요
완전탐색으로 다 비교했습니다.
- #93 
- #94
> [23-02-14] doha.py

- Programmers - 고득점 Kit/[DP] 정수 삼각형/hyuksoon.py
- Programmers - 고득점 Kit/[완전탐색] 모의고사/hyuksoon.py
- 모의고사
완탐!
- 정수 삼각형
조금이라도 응용된다면 풀지 못할 문제..
- #94
- #93
> [23-02-14] hyuksoon.py

- Programmers - 고득점 Kit/[DFS-BFS] 게임 맵 최단거리/seungyeon.py
- Programmers - 고득점 Kit/[DP] 정수 삼각형/seungyeon.py
- Programmers - 고득점 Kit/[그리디] 구명보트/seungyeon.py
- Programmers - 고득점 Kit/[완전탐색] 모의고사/seungyeon.py
- 완전 탐색 .... 완전 탐색 .. 
- 반복문을 이용해 점점 숫자를 알아가는 DP
- 마지막 depth에서 가장 큰 값
- #93 
- #94
> [23-02-14] seungyeon.py

- Programmers - 고득점 Kit/[DFS-BFS] 게임 맵 최단거리/kyuhyun.py
- Programmers - 고득점 Kit/[그리디] 구명보트/kyuhyun.py
1. 게임 맵 최단거리
- BFS 로 풀었습니다
2. 구명보트
- 그리디, deque 이용했습니다
- #100 
- #101
> [23-02-15] kyuhyun.py

- Programmers - 고득점 Kit/[DFS-BFS] 게임 맵 최단거리/dain.js
- Programmers - 고득점 Kit/[그리디] 구명보트/dain.js
🥲 python은 신이다!
- **게임 맵 최단거리** :  
처음에 그냥 dfs 하고싶었는데, 방문정보가 독립적이어야해서 deepcopy를 쓰려고 봤더니 직접 구현해야하는 자스는 멋지다.  
그래서 안썼다.
bfs로 풀었는데. 시간초과 해결 못함. 아마 python에서는 되는 코드 아닐랑구.
- **구명보트** : 그리디로 풀었다. 테케는 맞는데 자꾸 틀려서 왜인지 찾아보니 자바스크립트의 sort는 문자열 기준... (TMI)
```js
arr = [140, 130, 120, 40, 30, 20]
arr.sort() // [120,130,140, 20, 30, 40]
arr.sort((a,b)=>(a-b)) // [20, 30, 40, 120, 130, 140] 비교 함수를 사용해서 숫자형으로 비교시키기
```
- #100 
- #101
> [23-02-15] dain.js

- Programmers - 고득점 Kit/[DFS-BFS] 게임 맵 최단거리/seungyeon.py
- Programmers - 고득점 Kit/[DP] 정수 삼각형/seungyeon.py
- Programmers - 고득점 Kit/[그리디] 구명보트/seungyeon.py
pull request 이슈가 있어 14일 커밋도 함께 올라가네요 하하 .. 
- 전형적인 bfs 문제 nx,ny를 이용한 문제 
- 처음엔 pop 생각했다가 두번째엔 큰것부터 옮겼다가 세번째엔 큰거랑 작은거 같이 옮겼어요
- #93 
- #100
- #101
> [23-02-15] seungyeon.py

- Programmers - 고득점 Kit/[DFS-BFS] 게임 맵 최단거리/hyuksoon.py
- Programmers - 고득점 Kit/[그리디] 구명보트/hyuksoon.py
- 게임 맵 최단거리
bfs
- 구명보트
그리디, 큐
- #100
- #101
> [23-02-15] hyuksoon.py

- Leet Code/Two Sum/kyuhyun.py
- Programmers - 고득점 Kit/[DP] 등굣길/kyuhyun.py
1. Two Sum
- 걍 심플하게 for문 돌리면서 나머지 값 찾았어요,,
2. 등굣길
- DP답게 초반에 뻘짓으로 시간 좀 낭비하고, 고민하다 보니 그냥 주어진 격자안에서만 해결하면 되는 문제였습니다.
- #107 
- #108
> [23-02-16] kyuhyun.py

- Leet Code/Two Sum/seungyeon.py
- Programmers - 고득점 Kit/[동적계획법] 등굣길/seungyeon.py
- 오 리트코드는 solution 정의가 신기하게 되어있네요 
- 점화식만 잘 생각한다면 .. 
- 아 근데 함정도 있었다 
- #107 
- #108
> [23-02-16] seungyeon.py

- Leet Code/Two Sum/hyuksoon.py
- 등굣길
뭐 어케 푸는건데 ㅠ
- 투썸 (place)
투포인터
- #107 
- #108
> [23-02-16] hyuksoon.py

- Programmers - 고득점 Kit/[이분탐색] 징검다리/kyuhyun.py
1. 징검다리
- 핵심은 n을 기준으로 mid 값과 비교하는 것입니다.
- mid를 설정한 후 그 사이에 지워야하는 돌이 몇개인지 카운트해서 풀었습니다~.~
- #112
> [23-02-20] kyuhyun.py

- Programmers - 고득점 Kit/[이분탐색] 징검다리/hyuksoon.py
- 징검다리
이분탐색
코드를 줄일 수 있는 여지가 있지 않을까?? 잘 모르겠음,,
- #112
> Create [이분탐색] 징검다리 hyuksoon.py

- Programmers - 고득점 Kit/[그래프] 순위/kyuhyun.py
- 핵심은 만약 A가 B를 이기고 B가 C를 이겼다면 A는 C도 이긴거다,,인데 이걸 구현하려고 딕셔너리에 이긴목록 진목록 다 저장하고 이러쿵저러쿵 하다보니까 됐어요,,넘 어렵네요,,
- #116
> [23-02-21] kyuhyun.py

- Programmers - 고득점 Kit/[그래프] 순위/doha.py
노가다 느낌으로 비효율적이라고 생각하긴 하는데 풀렸다면 ok입니다
- #116
> [23-02-21] doha.py

- Programmers - 고득점 Kit/[이분탐색] 징검다리/seungyeon.py
> [23-02-20] seungyeon.py

- Programmers - 고득점 Kit/[그래프] 순위/hyuksoon.py
- Programmers - 고득점 Kit/[스택-큐] 프린터/hyuksoon.py
- 순위
처음엔 위상정렬 느낌을 생각했지만 모르겠어서 야매로 품 ㅎㅎ!,,,
- #116
> [23-02-21] hyuksoon.py

- Programmers - 고득점 Kit/[스택-큐] 프린터/kyuhyun.py
- Programmers - 고득점 Kit/[해시] 위장/kyuhyun.py
1. 위장
- 딕셔너리에 넣어주고, (a+1)(b+1)(..) -1 계산 했습니다
2. 프린터
- 인덱스랑 우선순위 deque에 넣어주고, 우선순위 배열 정렬해서 [-1]이랑 비교했습니다
- #121 
- #122
> [23-02-22] kyuhyun.py

- Programmers - 고득점 Kit/[그래프] 순위/seungyeon.py
- Programmers - 고득점 Kit/[스택-큐] 프린터/seungyeon.py
- Programmers - 고득점 Kit/[해시] 위장/seungyeon.py
- 딕셔너리 사용
- 배열을 pop
- #121
- #122
> [23-02-22] seungyeon.py

- Programmers - 고득점 Kit/[완전탐색] 카펫/seungyeon.py
- Programmers - 고득점 Kit/[힙] 이중우선순위큐/seungyeon.py
> [23-02-23] seungyeon.py

- Programmers - 고득점 Kit/[완전탐색] 카펫/hyuksoon.py
- Programmers - 고득점 Kit/[힙] 이중우선순위큐/hyuksoon.py
- 카펫
이게 맞나.. 완탐으로 어케푸는진 모르겠어요
- 이중우선순위큐
최대힙, 최소힙 컨셉은 맞는거 같은데 코드가 너무 더러워요😢
- #127 
- #128
> [23-02-23] hyuksoon.py

- Programmers - 고득점 Kit/[완전탐색] 카펫/kyuhyun.py
- Programmers - 고득점 Kit/[힙] 이중우선순위큐/kyuhyun.py
1. 이중우선순위큐 
- 약간 야매로 풀었어요,,
2. 카펫
- 그냥 수학문제,,
- #127 
- #128
> [23-02-23] kyuhyun.py

- Programmers - 고득점 Kit/[스택-큐] 프린터/doha.py
- Programmers - 고득점 Kit/[해시] 위장/doha.py
- **1차 시도** : combination 사용해서 1가지일때, 2가지일때, 2가지 이상일때 각각 구해서 막 더하고 그랬는데 시간초과..
- **2차 시도** : 손으로 쓰면서 규칙 찾으려고 1시간 가까이 노트 끼적끼적하다가 찾음  
(각 조합별 길이 + 각 아이템을 착용 안했을 경우) 만큼 전부 곱해주고 그럼 전부 착용 안한 경우(한가지)만 빼주면 끝.  
문제 처음 봤을때는 쉽게 느껴졌는데 시간초과때문에 오래걸린 케이스  
개인적으로 이런 테스트케이스 맘에 안들어요 더 추가됐으면 좋겠다
딕셔너리를 사용해서 풀긴했는데, 좀 코드가 난해해서
스택이나 큐를 사용한 사람이 설명해주겠지 하고있습니다.
- #121 
- #122
> [23-02-22] doha.py

- Programmers - 고득점 Kit/[완전탐색] 카펫/dain.py
- Programmers - 고득점 Kit/[힙] 이중우선순위큐/dain.py
- **카펫** : 노란색 영역의 높이를 기준으로 돌며 탐색했습니다~
- **이중우선순위큐** : 프로그래머스 지금 테스트케이스가 부족해서 정답이 되었지만, 막히지 않을까...!
- #127 
- #128
> [23-02-23] dain.py

- Programmers - 고득점 Kit/[그리디] 섬 연결하기/hyuksoon.py
- 섬 연결하기
최소신장트리(이름맞나) 같았는데 그리디라고 써있기도 하고 기억도 안나서 야매로 구현했습니다
근데 저번에 다인님 코드에서 힌트 얻었어요 이게 스터디의 힘인가,,?
- #133
> [23-02-24] hyuksoon.py

- Programmers - 고득점 Kit/[그리디] 섬 연결하기/kyuhyun.py
- 시작 노드는 0으로 고정하고 접근 가능한 노드들간의 거리중 가장 작은 걸 택했어요
- #133
> [23-02-24] kyuhyun.py

- Programmers - 고득점 Kit/[그리디] 섬 연결하기/doha.py
모든 정점 연결하는 알고리즘 -> **크루스칼 알고리즘** 입니다
이거 모른채로, 다익스트라 사용해서 막 구현하는데 죽어도 안풀리길래 노선을 변경했습니다
이렇게 허무하게 풀리다니..
- #133
> [23-02-24] doha.py

- Programmers - 고득점 Kit/[그래프] 방의 개수/dain.py
- Programmers - 고득점 Kit/[그리디] 섬 연결하기/dain.py
- **섬 연결하기**  
언젠가 공부해야했을 크루스칼 알고리즘 이 기회에 공부해서 좋았다!  
크루스칼은 저런 생각을 어떻게 하는걸까...🤔
- #133
> [23-02-24] dain.py

- Programmers - 고득점 Kit/[그래프] 방의 개수/doha.py
대각선이 교차점에 포함이 안되는 경우를 고민하다가  
저번에 스프링코딩때 만났던 문제랑 유사해서 그때 풀이법 찾아본게 도움이 많이 됐습니다  
좀 비효율 적이어도, 모든 값을 두번씩 돌리면 되지 않을까? 해서 해결하긴 했는데  
시간은 좀 오래걸리더라구요 레벨 5치고는 할만했지만, 그래도 많이 어려웠다
- #138
> [23.03.02] doha.py

- Programmers - 고득점 Kit/[그래프] 방의 개수/seungyeon.py
문제는 이해 했는데 .. 어디서부터 손 대야할지 전혀 1도 감이 안잡혀요 ... 
- #138
> [23-03-02] seungyeon.py

- Programmers - 고득점 Kit/[그래프] 방의 개수/hyuksoon.py
-방의 개수
뭐라도 볼걸 아무것도 안보고 객기부리다가 못품...
같은 간선, 대각선, 또 뭐있는거임 ㅜ..?
- #138
> [2023-03-02] hyuksoon.py

- Programmers - 고득점 Kit/[그래프] 방의 개수/kyuhyun.py
- 방이 생기는 경우는  다 고려를 했는데 대각선 케이스 구현을 고민하다가,,,
- 답이 안나와서 힌트 살짝쿵 봤습니다,, 2씩 움직이면 되더라구요 하하하 shit
- #138
> [23-03-02] kyuhyun.py

- Programmers - 고득점 Kit/[DFS-BFS] 네트워크/dain.py
- Programmers - 고득점 Kit/[그래프] 방의 개수/dain.py
- Programmers - 고득점 Kit/[해시] 베스트앨범/dain.py
- **방의 개수**
- 음... 그래프가 맞긴 한데... 그래프... 음
- **Rule 1 : 기존에 방문한 점과, 새롭게 연결되면 방이 생긴다.**
- **Rule 2 :대각선과 대각선이 교차하면 방이 하나 생긴다.**
- 이 두 가지의 if/else 케이스를 정리를 못해서 헤맸습니당
- 풀고나서 보니 2칸씩 가는 코드가 간결한 방법이 있네요! 이렇게 또 배워갑니다🥳
- **(추가) 오일러 정리** 를 이용한 풀이
- 오일러 정리 : https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=a4gkyum&logNo=150165179646
- 이를 이용한 코드 추가해두었습니다.
- #138
> [23-03-02] dain.py

- Programmers - 고득점 Kit/[그래프] 방의 개수/dain.py
> :memo: reupload 23-03-02 dain.py

- Programmers - 고득점 Kit/[DFS-BFS] 네트워크/dain.py
- Programmers - 고득점 Kit/[해시] 베스트앨범/dain.py
- ✨ 효과 만점 코딩테스트 Cheat Sheet!/🚀 알고리즘 해킹 아이디어.md
- **베스트앨범**
완죠니 해시 / 정렬 문제
어 이 문제 풀었었는데... 어디서 풀었더라...? 어떻게 하는거더라...?  
하고 처음 푸는 것처럼 풀었습니다 ^___^
- **네트워크**
최근에 섬연결하기 문제에서 사용한 `크루스칼 알고리즘`의 기초가 되는 `union-find` 를 적용하면 된다는 것은 알겠는데
어떡하지~ 하고 코드 안짜고 빈둥대다가 bfs 적용하니까 되네욤!
- **🚀 알고리즘 해킹 아이디어**  
치트시트를 추가했습니다! (지난 시간, 교점 체크를 위해 좌표 평면 두 배로 늘리는 것)
- #145 
- #146
> [23-03-06] dain.py

- Programmers - 고득점 Kit/[DFS-BFS] 네트워크/seungyeon.py
- Programmers - 고득점 Kit/[해시] 베스트앨범/seungyeon.py
1. zip(index,genres,plays) 실패
zip으로 엮어도, 장르별 해쉬 테이블 필요.
index = [ i for i in range(len(genres))]
2. 전체 재생횟수의 1,2위의 장르의 1등,2등 index
total, genre 2개의 딕셔너리 필요
zip으로 햇다가 dict으로 바꿨단 이야기 ~
저는 DFS가 좋아요 왜냐면 코드가 더 짱ㅂ기 때문에 
- #0
- #0
> [23-03-06] seungyeon.py

- Programmers - 고득점 Kit/[DFS-BFS] 네트워크/kyuhyun.py
- Programmers - 고득점 Kit/[해시] 베스트앨범/kyuhyun.py
1. 베스트앨범
- 딕셔너리도 정렬이 되는걸 처음 알았어요 
- 딕셔너리의 정렬을 요리조리 써보는데 시간을 많이 썼어요 유유 
2. 네트워크
- DFS로 풀었습니다
- #145
- #146
> [23-03-06] kyuhyun.py

- Programmers - 고득점 Kit/[DFS-BFS] 네트워크/hyuksoon.py
- Programmers - 고득점 Kit/[해시] 베스트앨범/hyuksoon.py
- 네트워크
bfs
- 베스트앨범
해시로 했는데 코드가 좀 더럽...ㅎㅎ
- #145 
- #146
> [23-03-06] hyuksoon.py

- Programmers - 고득점 Kit/[그리디] 단속카메라/hyuksoon.py
- Programmers - 고득점 Kit/[스택-큐] 다리를 지나는 트럭/hyuksoon.py
- Programmers - 고득점 Kit/[스택-큐] 주식가격/hyuksoon.py
- Programmers - 고득점 Kit/[완전탐색] 전력망을 둘로 나누기/hyuksoon.py
- Programmers - 고득점 Kit/[완전탐색] 피로도/hyuksoon.py
- 다리를 지나는 트럭
문제 이해 잘못해서 꽤 오래걸렸는데, 그냥 단순하게 하니깐 되네요
- 주식 가격
이거 비슷한거 있었던거 같은데 그때 도하가 굉장히 깔끔쓰하게 푸는법 알려줬던거 같은데 기억 안나서 그냥 때려박음 ㅜㅜ
- 전력망을 둘로 나누기
미리 연결시켜놓고, 끊을 지점(두 점) 에서부터 시작해서 이어진거 갯수 찾음
- 피로도
퍼뮤테이션
- 단속카메라
풀고나서 너무 허탈해서 화가났습니다🤬
- #153 
- #154 
- #155 
- #156 
- #157
> [23-03-09] hyuksoon.py

- Programmers - 고득점 Kit/[그리디] 카메라/seungyeon.py
- Programmers - 고득점 Kit/[스택-큐] 다리를 지나는 트럭/seungyeon.py
- Programmers - 고득점 Kit/[스택-큐] 주식가격/seungyeon.py
- Programmers - 고득점 Kit/[완전탐색] 전력망을 둘로 나누기/seungyeon.py
- Programmers - 고득점 Kit/[완전탐색] 피로도/seungyeon.py
- 1초에 하나라서 그거 고려하기 좀 어려웟엉요
- 오 그냥 완전 탐색
- dfs
- 좀 피곤하네요
- 그리디
- 구간을 벗어나는 시간에 초점을 맞추어
- 어려워요
- #156 
- #157 
- #155 
- #154 
- #153
> [23-03-09] seungyeon.py

- Programmers - 고득점 Kit/[그리디] 단속카메라/kyuhyun.py
- Programmers - 고득점 Kit/[스택-큐]  주식가격/kyuhyun.py
- Programmers - 고득점 Kit/[스택-큐] 다리를 지나는 트럭/kyuhyun.py
- Programmers - 고득점 Kit/[완전탐색] 전력망을 둘로 나누기/kyuhyun.py
- Programmers - 고득점 Kit/[완전탐색] 피로도/kyuhyun.py
1. 다리를 지나는 트럭
- 처음에 좀 복잡하게 생각 하다가 안풀려서 그냥 단순하게 다리를 만들었어요!,,,
2. 피로도
- 완탐 문제 답게 permutation 써서 다 해봤습니다
3. 주식가격
- 하나씩 돌면서 카운트 했는데 다행히 시간초과가 안뜨더라구요? 
4. 전력망을 둘로 나누기
- 이것도 그냥 combination 써서 다 돌렸습니다,,
5. 단속카메라
- 푼것 중에 제일 허무했어요,,
- #153 
- #154 
- #155 
- #156 
- #157
> [23-03-09] kyuhyun.py

- Programmers - 고득점 Kit/[DFS-BFS] 단어 변환/kyuhyun.py
- Programmers - 고득점 Kit/[DP] 사칙연산/kyuhyun.py
1. 사칙연산,,,,
2. 단어 변환
- DFS로 풀었습니다
- #163 
- #164
> [23-03-13] kyuhyun.py

- Programmers - 고득점 Kit/[DFS-BFS] 단어변환/seungyeon.py
- Programmers - 고득점 Kit/[DP] 사칙연산/seungyeon.py
- 어령워요
- 단어 1글자 다를 때
- #164 
- #163
> [23-03-13] seungyeon.py

- Programmers - 고득점 Kit/[DFS-BFS] 아이템 줍기/kyuhyun.py
- Programmers - 고득점 Kit/[DFS-BFS] 여행경로/kyuhyun.py
- Programmers - 고득점 Kit/[완전탐색] 모음사전/kyuhyun.py
1. 모음사전
- 완탐답게 product로 모든 경우 구해서  정렬 후 인덱스 반환했습니다.
2. 아이템 줍기
- 처음에 좀 복잡하게 생각하다가 그냥 단순하게 바깥, 테두리, 내부 각각 숫자 따로 설정해서 BFS로 했는데 틀리더라구요?
- 쭉 따라가보니 경로가 아닌 길로 탐색을 가길래 엇 길이 아닌 길? 저번에 2배 해준 그문제 생각나서 2배 해줬습니다아
3. 여행경로
- 엣지케이스 알아내는게 좀 힘들었어요,,,
- #169
- #170
- #171
> [23-03-16] kyuhyun.py

- Programmers - 고득점 Kit/[DFS-BFS] 여행경로/dain.py
- **모음사전** : combinations 로 풀었습니당
- **아이템 줍기** : 어려워... 모서리 포함 사각형 색칠하고, 모서리 제외 색칠하면 모서리 구할 수 있음...
- **여행경로** : 어려워... DFS...
두 문제가 이전 PR에 같이 들어가버림... 주의하겠움다💀
- #169 
- #170 
- #171
> [23-03-16] dain.py

- Programmers - 고득점 Kit/[DFS-BFS] 아이템 줍기/hyuksoon.py
- Programmers - 고득점 Kit/[DFS-BFS] 여행경로/hyuksoon.py
- Programmers - 고득점 Kit/[DFS-BFS] 퍼즐 조각 채우기/hyuksoon.py
- Programmers - 고득점 Kit/[DP] 도둑질/hyuksoon.py
- Programmers - 고득점 Kit/[완전탐색] 모음사전/hyuksoon.py
- 모음사전
이따구로 하는게 맞나..?
다섯개이므로 다섯번씩 써서 했음
- 아이템 줍기
이도하는 신인가..?
- 모음사전
잘 모르겠어서 브루트포스로 풀었슴다..
- #169 
- #170 
- #171
> [23-03-16] hyuksoon.py

- Leet Code/Two Sum/jamin.py
- Programmers - 고득점 Kit/[스택-큐] 같은 숫자는 싫어/jamin.py
- Programmers - 고득점 Kit/[스택-큐] 올바른 괄호/jamin.py
- Programmers - 고득점 Kit/[완전탐색] 모음사전/jamin.py
- Programmers - 고득점 Kit/[해시] 폰켓몬/jamin.py
- Warming Up/삼총사/jamin.py
- Warming Up/콜라 문제/jamin.py
1. 모음사전
중복 순열 이용해서 모든 경우 배열에 넣은 뒤 인덱스 검색
2. 아이템 줍기
ㅜㅜ...........................
3. 여행 경로
ㅜㅜ.....
4. 폰켓몬
종류 몇 가지인지 계산한 뒤 N/2보다 크면 N/2 반환, 작으면 종류 개수 반환
5. 올바른 괄호
( 이면 넣고 )이면 빼는데 남아있으면 false
6. 삼총사
number C 3 조합으로 풀었습니다
7. 콜라 문제
빈 병을 담아두는 변수 만들어둬서 빈 병 개수 정확하게
8. 같은 숫자는 싫어
전 숫자랑 다르면 넣어줌
- #169 
- #170 
- #171 
- #1 
- #2 
- #4 
- #6 
- #30
> [23-03-16] jamin.py

- Programmers - 고득점 Kit/[DP] 도둑질/kyuhyun.py
1. 도둑질
- 제 시간을 도둑당했어요,,,
- #179
> [23-03-20] kyuhyun

- Programmers - 고득점 Kit/[DFS-BFS] 퍼즐 조각 채우기/hyuksoon.py
- Programmers - 고득점 Kit/[DP] 도둑질/hyuksoon.py
죄성함다 풀리퀘를 안닫았었어요.. ㅎㅎ..
- 퍼즐 조각 채우기
진짜 조금만 더 생각하면 될거 같기도 한데 이 방법이 너무 비효율적이라 아닌거 같아서 놓아주었어요..잘가...
- 도둑질 
연결되었기에 경우의 수 생각하고 두번 돌림!
- #179 
- #180
> [23-03-20] hyuksoon.py

- Leet Code/Add Two Numbers/dain.py
- Leet Code/Longest Palindromic Substring/dain.py
- Leet Code/Longest Substring Without Repeating Characters/dain.py
- Leet Code/Two Sum/dain.py
- Programmers - 고득점 Kit/[DFS-BFS] 퍼즐 조각 채우기/dain.py
- Programmers - 고득점 Kit/[DP] 도둑질/dain.py
- **도둑질**
- DP를 이용해서 첫 집을 터는 경우와, 안터는 경우를 나누어 풀기.
- **퍼즐 조각 채우기**
- DFS,BFS 보다는 구현 문제에 가깝고, 내용이 많다... 알고리즘 측면에서 좋은 문제...는😵
- #180 
- #179
> [23-03-20] dain.py

- Leet Code/Longest Substring Without Repeating Characters/jamin.py
2. Add Two Numbers
- 문제 해석부터 어려웠어요 ㅜㅜ ㅜㅜ ㅜㅜㅜㅜㅜ .....
3. Longest Substring Without Repeating Characters
- 중복 문자 나오면 시작 인덱스를 갱신해주면서 풀었슴다
5. Longest Palindromic Substring
- ㅜㅜㅜㅜ.......... PR날짜도 323.. palindromic....
- #178
> [23-03-23] jamin.py

- Leet Code/Add Two Numbers/kyuhyun.py
- Leet Code/Longest Palindromic Substring/kyuhyun.py
- Leet Code/Longest Substring Without Repeating Characters/kyuhyun.py
> [23-03-23] kyuhyun.py

- Leet Code/Add Two Numbers/dain.py
- Leet Code/Longest Palindromic Substring/dain.py
- Leet Code/Longest Substring Without Repeating Characters/dain.py
- Programmers - 문제 풀이/광물 캐기/dain.py
- Programmers - 문제 풀이/짝지어 제거하기/dain.py
- Programmers - 문제 풀이/최댓값과 최솟값/dain.py
- **Longest Substring Without Repeating Characters** : 약간 stack 느낌
- **Longest Palindromic Substring**: 효율성이... 리스트로 풀면 시간초과 떠요. 문자열로...
- **Add Two Numbers**:제대로 못 푼듯... 더 정리할 수 있을 것 같은데😵 이게 제일 어렵네요
- #178 
- #181 
- #186
> [23-03-23] dain.py

- Leet Code/Add Two Numbers/hyuksoon.py
- Leet Code/Longest Palindromic Substring/hyuksoon.py
- Leet Code/Longest Substring Without Repeating Characters/hyuksoon.py
- Add Two Numbers
갱장히 까다로웠음 자료구조 수업 듣는 기분 새록새록
- Longest Substring Without Repeating Characters
정석이 기억이 안나서 딕셔너리로 풀었습니다
- Longest Palindromic Substring
어케 풀까 하다가 디피로 풀고 싶었는데 모르겠어서 투포인터로 풀었습ㄴ다 분명 예전에 디피로 플어본 적 있었던거 같은데 점점 기억력 퇴화..
- #178
- #181 
- #186
> [23-03-23] hyuksoon.py

- Programmers - 문제풀이/광물 캐기/jamin.py
- Programmers - 문제풀이/최댓값과 최솟값/jamin.py
1. 광물캐기
- 광물을 5개 이하로 묶어서 돌 곡괭이 기준 피로도 가장 높은 순으로 정렬한 뒤 피로도 계산. key로 정렬하는 것을 사용하게 돼서 반가웠어욥. 근데 막판에 갑자기 picks도 minerals처럼 광물 이름으로 주어진다고 착각해서 결과 피로도 계산 부분을 삽질.. 깨닫고 나니 스터디 시간,....
2. 최댓값 최솟값
- map이용해서 다 int로 넣어준 뒤 최대최소 찾고 반환
- #193 
- #194
> [23-03-27] jamin.py

- Programmers - Lv.2/최댓값과 최솟값/jiwon.py
- Programmers - 문제풀이/광물 캐기/jiwon.py
- Programmers - 문제풀이/최댓값과 최솟값/jiwon.py
- 광물 캐기
어떻게 풀어야 될지 몰라서 막 풀었어요,.,
- 최댓값과 최솟값
int형 리스트로 바꾸고 최댓값 최솟값 구했습니다
- #193 
- #194
> [23-03-27] jiwon.py

- Programmers - 문제풀이/괄호 회전하기/jamin.py
- Programmers - 문제풀이/귤 고르기/jamin.py
- Programmers - 문제풀이/짝지어 제거하기/jamin.py
1. 짝지어 제거하기
- 스택
2. 귤 고르기
- 종류별 갯수 구한 뒤 오름차순으로 정렬해서 차례대로 더하다가 K보다 크거나 같아질 때 귤의 종류 반환. Counter를 몰라서 직접 구했다가 나중에 알아서 약간 수정했어요ㅠ
3. 괄호 회전하기
- rotate(-1)로 계속 회전시켜주면서 체크
- #195 
- #196 
- #197
> [23-03-30] jamin.py

- Programmers - 문제 풀이/괄호 회전하기/dain.py
- Programmers - 문제 풀이/광물 캐기/dain.py
- Programmers - 문제 풀이/귤 고르기/dain.py
- Programmers - 문제 풀이/짝지어 제거하기/dain.py
- Programmers - 문제 풀이/최댓값과 최솟값/dain.py
- **짝지어 제거하기** : stack ⭐
- **귤 고르기** : 종류를 개수가 많은 순으로 정렬
- **괄호 회전하기** : 짝지어 제거하기 문제 반복하기 ⭐⭐
- #195 
- #196 
- #197
> [23-03-30] dain.py

- Programmers - 문제 풀이/광물 캐기/dain.py
- Programmers - 문제 풀이/최댓값과 최솟값/dain.py
- **광물 캐기** : Lv3 가셔도 될듯. 완탐 하면 시간초과😵, 그리디.
- **최댓값과 최솟값** : 이게... 행복?🥳
- #193 
- #194
> [23-03-27] dain.py

- Leet Code/Longest Substring Without Repeating Characters/hyuksoon.py
- Programmers - 문제풀이/괄호 회전하기/hyuksoon.py
- Programmers - 문제풀이/광물 캐기/hyuksoon.py
- Programmers - 문제풀이/귤 고르기/hyuksoon.py
- Programmers - 문제풀이/짝지어 제거하기/hyuksoon.py
- Programmers - 문제풀이/최댓값과 최솟값/hyuksoon.py
- 광물캐기
그리디+정렬??
- 최댓값과 최솟값
문자열..?
달달하네요..🍫
- #193 
- #194
> [23-03-27] hyuksoon.py

- Programmers - 문제풀이/3 x n 타일링/kyuhyun.py
- Programmers - 문제풀이/과제 진행하기/kyuhyun.py
1. 3xn 타일링
- DP
2. 과제 진행하기
- 머리가 빙글빙글~~
- #208 
- #209
> [23-04-03] kyuhyun

- Programmers - 문제풀이/과제 진행하기/jamin.py
1. 과제 진행하기
- 제 코드에 제가 당햇서여,..
2. 3xn..
- ㅜㅜ
- #208
> [23-04-03] jamin.py

- Programmers - 문제 풀이/3 x n 타일링/hyuksoon.py
- Programmers - 문제 풀이/과제 진행하기/hyuksoon.py
- 과제 진행하기 : 스택,,?
- 3 x n 타일링 : 디피
- #209 
- #208
> [23-04-03] hyuksoon.py

- Programmers - 문제풀이/땅따먹기/kyuhyun.py
- Programmers - 문제풀이/문자열 압축/kyuhyun.py
- Programmers - 문제풀이/숫자 변환하기/kyuhyun.py
1. 숫자 변환하기
- 뭔가 어디서 풀어본것만 같은,,,
2. 문자열 압축
- 너무 쫄았다
- 뭔가 효울적으로 쪼개는 방법이 있을 것 같은데 모르겠어요ㅠㅜ
3. 땅따먹기
- 이것도 dp였네,,,
- #210 
- #211 
- #212
> [23-04-06] kyuhyun.py

- Programmers - 문제풀이/땅따먹기/jamin.py
- Programmers - 문제풀이/문자열 압축/jamin.py
1. 땅따먹기
- 4열밖에 안돼서 노가다로.. 풀었어요..! 
2. 문자열 압축
- 문자열 슬라이싱을 열심히 활용했습니다.
3. 숫자 변환하기
- 죄송합니돠 ㅜㅜ
- #211 
- #212 
- #210
> [23-04-07] jamin.py

- Programmers - 문제 풀이/땅따먹기/hyuksoon.py
- Programmers - 문제 풀이/숫자 변환하기/hyuksoon.py
- 숫자 변환하기
좋았음
- 땅따먹기
좋았음
- 문자열 압축
..양심적으로 벌금 내겠음..
- #210 
- #211
-  #212
> [23-04-06] hyuksoon.py

- Programmers - 문제풀이/교점에 별 만들기/kyuhyun.py
- Programmers - 문제풀이/디펜스 게임/kyuhyun.py
1. 디펜스 게임
- heap
2. 교점에 별 만들기
- 갓다인
- #223 
- #224
> [23-04-10] kyuhyun.py

- Programmers - 문제풀이/교점에 별 만들기/jamin.py
- Programmers - 문제풀이/디펜스 게임/jamin.py
1. 디펜스 게임
- 최대 힙
2. 교점에 별 만들기
- 다인 언니가 공유해주신 zip!!!과 is_integer()를 사용하였습니다
- #223 
- #224
> [23-04-10] jamin.py

- Programmers - 문제 풀이/교점에 별 만들기/hyuksoon.py
- Programmers - 문제 풀이/디펜스 게임/hyuksoon.py
- Programmers - 문제 풀이/문자열 압축/hyuksoon.py
- 디펜스 게임
heap하게 풀었음 ㅋ.ㅋ
- 교점에 별 만들기
*"킹다인"*
- #223 
- #224
> [23-04-10] hyuksoon.py

- Programmers - 문제풀이/교점에 별 만들기/jiwon.py
- Programmers - 문제풀이/디펜스 게임/jiwon.py
- Programmers - 문제풀이/무인도 여행/jiwon.py
- Programmers - 문제풀이/시소 짝꿍/jiwon.py
- Programmers - 문제풀이/할인 행사/jiwon.py
- 디펜스 게임
최대힙 이용
- 교점에 별 만들기
문자열 이용
- #223 
- #224
> [23-04-10] jiwon.py

- Programmers - 문제풀이/무인도 여행/jiwon.py
- Programmers - 문제풀이/시소 짝꿍/jiwon.py
- Programmers - 문제풀이/할인 행사/jiwon.py
-시소짝꿍 : counter
- 할인행사: queue 사용
- 무인도 여행: bfs
- #225 
- #226 
- #227
> [23-04-14] jiwon.py

- Programmers - 문제풀이/무인도 여행/kyuhyun.py
- Programmers - 문제풀이/할인 행사/kyuhyun.py
1. 무인도 여행
- bfs
2. 할인 행사
- 딕셔너리
- #0
- #0
> [23-04-13] kyuhyun.py

- Programmers - 문제풀이/무인도 여행/jamin.py
- Programmers - 문제풀이/시소 짝꿍/jamin.py
- Programmers - 문제풀이/할인 행사/jamin.py
1. 시소 짝꿍
- counter()를 이용해 무게의 종류만 따졌다
2. 할인 행사
- zip()으로 리스트를 만들고, 리스트 10개씩 슬라이싱해서 비교
3. 무인도 여행
- BFS
- #225
- #226 
- #227
> [23-04-13] jamin.py

- Programmers - 문제풀이/두 원 사이의 정수 쌍/jamin.py
- Programmers - 문제풀이/야근 지수/jamin.py
- Programmers - 문제풀이/인사고과/jamin.py
> [23-04-27] jamin.py

- Programmers - 문제풀이/두 원 사이의 정수 쌍/hyuksoon.py
- Programmers - 문제풀이/야근 지수/hyuksoon.py
- Programmers - 문제풀이/인사고과/hyuksoon.py
- 인사고과
이 친구는 솔직히 힌트를 조금 받았습니다...
도무지 시간초과를 해결할 방법이 생각이 안났어요
결론은 정렬을 시키되, 0번째꺼를 내림차순, 1번째꺼를 오름차순으로 정렬시키면, 1번째 인덱스가 다르면 작다 가 보장되더라구요
- 야근 지수
최대힙을 사용했습니다
힙에서 pop -> 팝 한게 0보다 크면 -1해서 다시 힙에 푸쉬 -> 0보다 작거나 같으면 0보다 큰게 나올 때 까지 pop
힙 루프 돌면서 제곱해서 합산
- 두 원 사이의 정수 쌍
이것도 시간초과땜에 화났는데 조금만 생각해보니깐 모든 좌표를 돌 필요가 없더라구요
원 방정식을 이용해서 큰 원과 작은원 사이에 있는 값의 범위를 찾았습니다
1사분면? 맞나 암튼 사분면 하나만 구하고 *4 했어요
- #239
- #240 
- #241
> [23-04-27] hyuksoon.py

- Programmers - 문제풀이/기둥과 보 설치/jiwon.py
- Programmers - 문제풀이/두 원 사이의 정수 쌍/jiwon.py
- Programmers - 문제풀이/야근 지수/jiwon.py
- Programmers - 문제풀이/인사고과/jiwon.py
- 두 원 사이 정수 쌍
시간 초과나는데,, 어떻게 해야할지 모르겠어요,,
- 야근 지수
최대 힙으로 풀었습니다
- 인사고과
검색의 힘을 빌렸습니다,, 정렬해서 비교
- #239 
- #240 
- #241
> [23-04-37] jiwon.py

- Programmers - 문제풀이/기둥과 보 설치/jamin.py
> [23-05-01] jamin.py

- Programmers - 문제풀이/기둥과 보 설치/hyuksoon.py
- 기둥과 보 설치
복귀전 장렬하게 전사.
근데 테스트 케이스 안주는게 진짜 치사하다
- #245
> [23-05-01] hyuksoon.py

- Programmers - 문제풀이/멀쩡한 사각형/jiwon.py
- Programmers - 문제풀이/최고의 집합/jiwon.py
- Programmers - 문제풀이/호텔 대실/jiwon.py
- 최고의 집합
원소들이 비슷한 수를 가지게끔 풀었어요
- 호텔 대실
힙을 이용해서 풀었습니다
- 멀쩡한 사각형
일차 방정식으로 풀려했는데 도저히 생각이 나지 않아요,,
- #249 
- #250 
- #251
> [23-05-04] jiwon.py

- Programmers - 문제풀이/최고의 집합/kyuhyun.py
- Programmers - 문제풀이/호텔 대실/kyuhyun.py
1. 호텔 대실
- 힙으로 풀었습니당
2. 최고의 집합
- 잡합이라 해노코 중복이 허용이라니,,
- #250 
- #249
> [23-05-04] kyuhyun.py

- Programmers - 문제풀이/미로 탈출/kyuhyun.py
> [23-05-08] kyuhyun.py

- Programmers - 문제풀이/124 나라의 숫자/jiwon.py
- Programmers - 문제풀이/불량 사용자/jiwon.py
- Programmers - 문제풀이/테이블 해시 함수/jiwon.py
- 테이블 해시 함수
정렬 후 ^로 계산
- 124 숫자의 나라
3의 배수일때와 아닐때 나눠서 계산
- 불량 이용자
user_id를 사전순 정렬 후 길이로 정렬해서 banned_id와 비교해서 풀라했는데 못풀겠어요,,
- #259 
- #260 
- #261
> [23-05-11] jiwon.py

- Programmers - 문제풀이/124 나라의 숫자/jamin.py
- Programmers - 문제풀이/테이블 해시 함수/jamin.py
- 124 나라의 숫자
규칙을 찾아 재귀적으로 풀었습니다
- 테이블 해시 함수
XOR연산하는 함수 reduce()..
- 불량사용자
문제가 불량해요 ..ㅜㅜ실패
- #260 
- #259
> [23-05-11] jamin

- Programmers - 문제풀이/무인도 여행/dain.py
- Programmers - 문제풀이/시소 짝꿍/dain.py
- Programmers - 문제풀이/할인행사/dain.py
- **시소 짝꿍** | EZ 🥳
- **할인행사** | sliding window + dictionary 풀긴 풀었는데 리팩토링 할 수 있을 것 같은데 시간관계상 패스😵
- **무인도 여행** | 완전 탐색으로 풀었는데 마음에 안들어요😵
- #225 
- #226 
- #227
> [23-04-13] dain.py

- Programmers - 문제풀이/숫자 게임/jamin.py
- Programmers - 문제풀이/혼자 놀기의 달인/jamin.py
- 혼자 놀기의 달인
연 상자는 숫자 0으로 바꿔주어 표시해주어 풀었습니다
- 숫자 게임
A와 B를 내림차순 정렬한 뒤 길이만큼 반복하되, B가 이긴경우에만 B의 인덱스를 1씩 증가시켜줌
- #266
- #265
> [23-05-15] jamin

- Programmers - 문제풀이/숫자 게임 /kyuhyun.py
- Programmers - 문제풀이/테이블 해시 함수/kyuhyun.py
- Programmers - 문제풀이/혼자 놀기의 달인/kyuhyun.py
> [23-05-15] kyuhyun.py

- Programmers - 문제풀이/숫자 게임/jiwon.py
- Programmers - 문제풀이/혼자 놀기의 달인/jiwon.py
- 숫자 게임
A 정렬하고, B 힙 써서 풀었습니다.
- 혼자 놀기의 달인
visited 리스트 만들어서 상자 하나씩 열어줬어요.
- #265 
- #266
> [23-05-15] jiwon.py

- Programmers - 문제풀이/연속 펄스 부분 수열의 합/jiwon.py
- Programmers - 문제풀이/예상 대진표/jiwon.py
- Programmers - 문제풀이/의상/jiwon.py
- 예상 대진표
a,b 차이가 1이 될 때까지 나누기 2 해줬습니다
- 연속 펄스 부분 수열의 합
시간 초과 못잡겠어서 검색해서 풀었습니다ㅎ. dp 이용했어요
- 의상
딕셔너리 사용해서 종류별로 개수 세줬습니다
- #269 
- #270 
- #271
> [23-05-18] jiwon.py

- Programmers - 문제풀이/예상 대진표/jamin.py
- Programmers - 문제풀이/의상/jamin.py
- 의상
해시, 다항식의 곱^^
- 예상 대진표
올림을 이용
- 연속펄스..
죄송함미돠 ㅜ.ㅜ
- #269 
- #271 
- #270
> [23-05-18] jamin

- Programmers - 문제풀이/연속 펄스 부분 수열의 합/dain.py
- Programmers - 문제풀이/예상 대진표/dain.py
- Programmers - 문제풀이/의상/dain.py
- **의상** : 경우의 수 계산
- **연속 펄스 부분 수열의 합** : 펄스 곱한 수열에서 구간합 최대값 구하기 (dp)
- **예상 대진표** : 번호 같아질 때 까지 나누기
- #269 
- #270 
- #271
> [23-05-18] dain.py

- Baekjoon - 문제풀이/A와 B 2/jiwon.py
- Baekjoon - 문제풀이/겹치는 건 싫어/jiwon.py
- Baekjoon - 문제풀이/문자열 게임 2/jiwon.py
- Baekjoon - 문제풀이/숨바꼭질 3/jiwon.py
- Baekjoon - 문제풀이/주식/jiwon.py
- Baekjoon - 문제풀이/줄세우기/jiwon.py
- Baekjoon - 문제풀이/지름길/jiwon.py
- Baekjoon - 문제풀이/컨베이어 벨트 위의 로봇/jiwon.py
- Baekjoon - 문제풀이/회전 초밥/jiwon.py
- Programmers - 문제풀이/리코쳇 로봇/jiwon.py
- Programmers - 문제풀이/부대복귀/jiwon.py
- Programmers - 문제풀이/요격 시스템/jiwon.py
- 숨바꼭질 3
bfs로 풀었는데, *2 하는 경우에 젤 먼저 처리해줘야 되는건 검색의 도움을 받았습니다 ^^;..
- 주식
주식 리스트를 거꾸로 탐색했어요
- A와 B 2
T를 S처럼 만들기 위해 조건에 맞게 재귀함수 호출하며 풀었습니다.
- 겹치는 건 싫어
못풀었어요,,, ㅠㅠ
- 회전초밥
set 사용해서 풀었어요
- 컨베이어 벨트 위의 로봇
deque 써서 rotate 해주면서 풀었습니다
- #283 
- #282 
- #286 
- #287 
- #288 
- #289
> [23-07-30] jiwon.py

- Baekjoon - 문제풀이/A와 B 2/kyuhyun.py
- Baekjoon - 문제풀이/겹치는 건 싫어/kyuhyun.py
- Baekjoon - 문제풀이/숨바꼭질3 /kyuhyun.py
- Baekjoon - 문제풀이/주식/kyuhyun.py
- Baekjoon - 문제풀이/회전 초밥/kyuhyun.py
1. 주식
- 거꾸로 가면서 계산
2. 숨바꼭질3
- BFS
- #282 
- #283
> [23-07-16] kyuhyun.py

- Baekjoon - 문제풀이/문자열 게임 2/jiwon.py
- Baekjoon - 문제풀이/볼 모으기/jiwon.py
- Baekjoon - 문제풀이/빗물/jiwon.py
- Baekjoon - 문제풀이/탑/jiwon.py
- 문자열 게임 2
K개 이상인 문자 dict 만들고, 인덱스 구해서 max,min 찾아서 풀었습니다
- 볼 모으기
stack 사용해서 4가지 케이스 구하고 min 찾아서 풀었습니다
- 빗물
한 블록 기준으로 왼쪽, 오른쪽 최대 구한 후 둘의 최소값 구함 -> 빗물이 담길 수 있는 용량. 이를 모든 블록에 대해 계산
- 탑
완전 탐색 시간 초과 -> stack 통해 풀이
- #291 
- #292
> [23-08-06] jiwon.py

- Baekjoon - 문제풀이/문자열 게임 2/yoonhyeong.py
- Baekjoon - 문제풀이/볼 모으기/yoonhyeong.py
- Baekjoon - 문제풀이/탑/yoonhyeong.py
- 문자열 게임 2
잘 모르겠어서 구글링 참고했습니다...
defaultdic에 K개 이상의 문자의 인덱스 저장 후에 길이 구했습니다.
- 볼 모으기
색깔마다 왼쪽으로 이동시킬 때, 오른쪽으로 이동시킬 때 경우의 수 중 
최솟값 구했습니다.
- #291 
- #292
> [23-08-06] yoonhyeong.py

- Baekjoon - 문제풀이/문자열 게임 2/kyuhyun.py
- Baekjoon - 문제풀이/문자열 교환/kyuhyun.py
- Baekjoon - 문제풀이/볼 모으기/kyuhyun.py
- Baekjoon - 문제풀이/빗물/kyuhyun.py
- Baekjoon - 문제풀이/인구 이동/kyuhyun.py
1. 볼 모으기
- 양쪽, 빨간색 파란색 전부 다 계산 후 최솟값 출력
2. 문자열 게임2
- 딕셔너리 이용
3. 문자열 교환
- a의 개수 만큼 이동하면서 b의 개수가 최소인 조합 찾기
4. 인구 이동
- BFS
- #291 
- #292 
- #295 
- #296
> [23-08-13] kyuhyun.py

- Baekjoon - 문제풀이/문자열 교환/yoonhyeong.py
- Baekjoon - 문제풀이/용액/yoonhyeong.py
- Baekjoon - 문제풀이/인구 이동/yoonhyeong.py
1. 문자열 교환
-  a의 갯수만큼 슬라이딩 윈도우로 b의 갯수가 최소인 경우 찾기
2. 인구 이동
-  이거 너무 어려워서 구글링 참고했습니다..  BFS로 연합 구역 탐색 후에 이동 시키기
- #295 
- #296
> [23-08-13] yoonhyeong.py

- Baekjoon - 문제풀이/전구와 스위치/yoonhyeong.py
- Baekjoon - 문제풀이/틱택토/yoonhyeong.py
1.  전구와 스위치
- 첫번째 스위치 기준으로 케이스 나눠서 풀었습니다
2. 틱택토 
-  주어진 테스트 케이스는 다 만족했는데 이상하게 10%에서 계속 틀렸다고 뜨네요.. 반례를 못찾겠습니다...
- #300 
- #301
> [23-08-21] yoonhyeong.py

- Baekjoon - 문제풀이/문자열 교환/jiwon.py
- Baekjoon - 문제풀이/용액/jiwon.py
- Baekjoon - 문제풀이/인구 이동/jiwon.py
- Baekjoon - 문제풀이/전구와 스위치/jiwon.py
- Baekjoon - 문제풀이/틱택토/jiwon.py
- 문자열 교환
rotate 써서 b 문자열 개수 확인
- 인구 이동
못풀었어요,,,
-> 저번주 코드리뷰&검색 통해서 bfs로 풀었어요
- 틱택토
진짜 왜 안되는지 모르겠어요,,,,ㅠㅠ
- 전구와 스위치
계속 생각했는데 도저히 생각이 안나서 검색 했습니다,,
- #295 
- #296 
- #300 
- #301
> [23-08-20] jiwon.py

- Baekjoon - 문제풀이/전구와 스위치/kyuhyun.py
- Baekjoon - 문제풀이/탑/kyuhyun.py
- Baekjoon - 문제풀이/틱택토/kyuhyun.py
1. 탑
- 스택 이용 했습니당
2. 전구와 스위치
- 뻘 짓 좀 하다가 케이스 나눠서 풀었습니다
- 코드가 깔끔하진 않아서 마음에 안드네요,,,
3. 틱택토
- 구현 문제
- 코드 왕복잡,,
- #300 
- #301
> [23-08-20] kyuhyun.py

- Baekjoon - 문제풀이/RGB 거리/yoonhyeong.py
- Baekjoon - 문제풀이/숫자고르기/yoonhyeong.py
1.  RGB 거리
-  두번째 줄부터 빨강, 초록, 파랑 선택했을 경우 나눠서 합으로 구했습니다.
2. 숫자고르기
-  DFS로 풀었습니다.
- #304 
- #305
> [23-08-27] yoonhyeong.py

- Baekjoon - 문제풀이/RGB거리/kyuhyun.py
- Baekjoon - 문제풀이/숫자 고르기/kyuhyun.py
1. RGB거리
- DP 로 최소값 누적해서 구했습니다
2. 숫자 고르기
- 사이클이 생기는 경우만 카운트 했습니다
- #304 
- #305
> [23-08-27] kyuhyun.py

- Baekjoon - 문제풀이/RGB거리/jiwon.py
- Baekjoon - 문제풀이/숫자고르기/jiwon.py
- RGB 거리
가장 작은 값들 더하면서 풀었어요
- 숫자 고르기
dict 선언후 values에 없으면 제거 반복했어요
- #304 
- #305
> [23-08-27] jiwon.py

- Baekjoon - 문제풀이/0 만들기/yoonhyeong.py
- Baekjoon - 문제풀이/녹색 옷 입은 애가 젤다지/yoonhyeong.py
- Baekjoon - 문제풀이/스카이라인 쉬운거/yoonhyeong.py
- Baekjoon - 문제풀이/영역 구하기/yoonhyeong.py
1.  스카이라인 쉬운거
-  높이를 스택에 담으면서 높이가 낮아지면  결과값 추가해서 풀었습니다.
2. 빌런 호석
- 각 숫자마다 바꿔야 하는 LED 갯수 구해서 이차원 배열로 풀려고 했으나 못풀었습니다 ㅠㅠ 
- #309 
- #310
> [23-09-03] yoonhyeong.py

- Programmers - 문제풀이/미로 탈출/hyuksoon.py
- Programmers - 문제풀이/숫자 게임/hyuksoon.py
- Programmers - 문제풀이/혼자 놀기의 달인/hyuksoon.py
- 미로 탈출
bfs 두번 돌렸슴다
visit 변수 초기화해줬어요
- #255
> [23-05-08] hyuksoon.py

- Baekjoon - 문제풀이/0 만들기/kyuhyun.py
- Baekjoon - 문제풀이/빌런 호석/kyuhyun.py
- Baekjoon - 문제풀이/스카이라인 쉬운거/kyuhyun.py
- Baekjoon - 문제풀이/영역 구하기/kyuhyun.py
1. 빌런호석
- 두 숫자 간의 패널차이를 먼저 구하고, 각 자리수 별로 비교 합 
2. 스카이라인 쉬운거
-  스택
- #310 
- #309
> [23-09-03] kyuhyun.py

- Baekjoon - 문제풀이/동전 1/kyuhyun.py
- Baekjoon - 문제풀이/좋다/kyuhyun.py
1. 동전 1
- DP
2. 좋다
- 이중 포인터
- #317 
- #318
> [23-09-16] kyuhyun

- Baekjoon - 문제풀이/동전 1/yoonhyeong.py
- Baekjoon - 문제풀이/부분합/yoonhyeong.py
- Baekjoon - 문제풀이/알파벳/yoonhyeong.py
- Baekjoon - 문제풀이/좋다/yoonhyeong.py
- Baekjoon - 문제풀이/포도주 시식/yoonhyeong.py
1. 동전 1
- 잘 모르겠어서 구글링 참고해서 풀었습니다 ㅠㅠ  DP로 풀었습니다. 
2. 좋다
-  투포인터
- #317 
- #318
> [23-09-17] yoonhyeong.py

- Baekjoon - 문제풀이/동전 1/jiwon.py
- Baekjoon - 문제풀이/부분합/jiwon.py
- Baekjoon - 문제풀이/알파벳/jiwon.py
- Baekjoon - 문제풀이/좋다/jiwon.py
- Baekjoon - 문제풀이/치킨 배달/jiwon.py
- Baekjoon - 문제풀이/포도주 시식/jiwon.py
- 동전 1
dp 생각은 했는데, 풀이를 못해서 검색했어요,,
- 좋다
투포인터 이용했습니다
- 부분합
투포인터 이용했습니다
- 알파벳
dfs 이용했는데, Python3으로 했더니 계속 시간초과 떠서 PyPy3으로 돌렸어요,,
- #317 
- #318
> [23-09-24] jiwon.py

- Baekjoon - 문제풀이/부분합/kyuhyun.py
- Baekjoon - 문제풀이/포도주 시식/kyuhyun.py
1. 부분합
- 투포인터
2. 포도주 시식
- DP
- #322
> [23-09-24] kyuhyun

- Baekjoon - 문제풀이/공유기 설치/yoonhyeong.py
- Baekjoon - 문제풀이/치킨 배달/yoonhyeong.py
1. 치킨 배달 
-  combination 함수 써서 풀었습니다.
2. 공유기 설치
- 이분 탐색으로 풀었습니다.
3. 불!
- 못 풀었습니다 ㅠㅠ
- #327 
- #325 
- #326
> [23-10-08] yoonhyeong.py
